name: Swift

on:
  push:
    branches: [ master,  Feature/Pub_UserManagement, Develop]
  pull_request:
    branches: [ master, Feature/Pub_UserManagement, Develop]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
