name: Swift

on:
  push:
    branches:
      -  master
      -  PubNubMessenger
      -  Develop
  pull_request:
    branches:
      -  master
      -  PubNubMessenger
      -  Develop

jobs:
  build:
    name: Build
    env:
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
    
    runs-on: macos-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: setup-cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        podfile-path: Podfile.lock

    - name: Install dependencies 
      run: | 
        pod install --repo-update
    - name: Build Proj
      run: |
        set -o pipefail && xcodebuild clean -workspace "Chat App.xcworkspace" -scheme "Chat App" -derivedDataPath $DERIVED_DATA_PATH build-for-testing CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" | xcpretty --color --simple
 #   - name: Run tests
 #     run: swift test -v