name: Swift

on:
  push:
    branches:
      -  master
      -  PubNubMessenger
      -  Develop
  pull_request:
    branches:
      -  master
      -  PubNubMessenger
      -  Develop

jobs:
  build:
    name: Build
    env:
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
    
    runs-on: macos-latest

    steps:
    - name: Checkout 
    - uses: actions/checkout@v2

    - name: Bundle Install
      run: bundle install 

    - name: Install dependencies 
      run: | 
        bundle exec pod install

    - name: Build Proj
      run: |
        set -o pipefail && xcodebuild clean -scheme "Chat App" -derivedDataPath $DERIVED_DATA_PATH build-for-testing | xcpretty --color --simple
 #   - name: Run tests
 #     run: swift test -v
