name: Swift

on:
  push:
    branches:
      -  master
      -  PubNubMessenger
      -  Develop
  pull_request:
    branches:
      -  master
      -  PubNubMessenger
      -  Develop

jobs:
  build:
    name: Build
    env:
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
    
    runs-on: macos-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2

#Access and retrieve dependency cache
#    - name: Get Cached Dependencies 
#Go here if dependency cache cannot be retrieved. 
    - name: setup-cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        podfile-path: Podfile.lock

#Cache dependencies.
    - name: Cache dependencies
      id: Cocoa-Cache
      uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}

    - name: CocoaPods
      if: steps.Cocoa-Cache.outputs.cache-hit != true
      run: | 
        pod install --repo-update

    - name: Install dependencies 
      run: | 
        pod install --repo-update
    - name: Build Proj
      run: |
        set -o pipefail && xcodebuild -workspace "Chat App.xcworkspace" -scheme "Chat App" -derivedDataPath $DERIVED_DATA_PATH build-for-testing CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" | xcpretty --color --simple