name: Swift

on:
  push:
    branches:
      -  master
      -  PubNubMessenger
      -  Develop
  pull_request:
    branches:
      -  master
      -  PubNubMessenger
      -  Develop

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
