name: Swift

on:
  push:
    branches:
      -  master
      -  PubNubMessenger
      -  Develop
  pull_request:
    branches:
      -  master
      -  PubNubMessenger
      -  Develop

jobs:
  build:
    name: Build
    env:
      SCHEME: "Actions"
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Proj
      run: |
        set -o pipefail && xcodebuild clean -scheme $SCHEME -destination $DESTINATION -derivedDataPath $DERIVED_DATA_PATH build-for-testing
 #   - name: Run tests
 #     run: swift test -v
