name: Swift

on:
  push:
    branches:
      -  master
      -  PubNubMessenger
      -  Develop
  pull_request:
    branches:
      -  master
      -  PubNubMessenger
      -  Develop

jobs:
  build:
    name: Build
    env:
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
    
    runs-on: macos-latest

#Checkout project
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

#Retrieve cached dependencies
     - name: Cache dependencies
       id: Cocoa-Cache
       uses: actions/cache@v1
       with:
         path: ./Pods/
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}

#Install dependencies
    - name: Install dependencies 
      run: | 
       bundle update
       bundle exec pod install --repo-update

#Bundle Install (Gemfile)
    - name: Bundle Install <Fastlane>
      run: bundle install

#Build Project
    - name: Build Proj
      run: |
        set -o pipefail && xcodebuild build -workspace "Chat App.xcworkspace" -scheme "Chat App" -derivedDataPath $DERIVED_DATA_PATH CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" | xcpretty --color --simple

#Execute tests through fastlane. 
    - name: Execute fastlane tests. 
      run: bundle exec fastlane test